#!/usr/bin/env bash
set -o pipefail

get_list() {
    list="$(dodona display)"
}

fzf_status=0
get_list

if grep --silent '^You can find' <<< "$list"; then
    dodona up
    get_list
fi

while ! grep --silent '^You can find' <<< "$list" && ((fzf_status == 0)); do
    list="$(echo "$list"; echo '        0: up')"
    selection="$(echo "$list" | grep -v '^$' | fzf --ansi --no-sort --reverse --header-lines 1 | sed -E 's/ +([0-9]+) *:.*/\1/')"
    fzf_status=$?
    if [[ $selection == '0' ]]; then
        dodona up
    elif [[ -n $selection ]]; then
        dodona select "$selection"
    fi
    get_list
done
